# Generated by Django 4.2.11 on 2025-01-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='original_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
