# Generated by Django 4.2.11 on 2025-01-19 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_profile_position'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='examiner',
            field=models.BooleanField(default=False, verbose_name='Экзаменатор'),
        ),
    ]
