# Generated by Django 4.2.11 on 2025-01-21 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_uploadedfile_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='rejected',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='rejected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
