# Generated by Django 4.2.11 on 2025-01-21 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_uploadedfile_approved_at_uploadedfile_rejected_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='direction',
            field=models.CharField(blank=True, choices=[('техническое', 'Техническое'), ('естественно-научное', 'Естественно-научное')], max_length=100, verbose_name='Направление'),
        ),
    ]
