# Generated by Django 4.2.11 on 2025-01-31 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_uploadedfile_direction'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='rejection_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отклонения'),
        ),
    ]
