# Generated by Django 4.2.11 on 2025-01-31 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_uploadedfile_rejection_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='scientific_examiner',
            field=models.BooleanField(default=False, verbose_name='Естественно-научный экзаменатор'),
        ),
        migrations.AddField(
            model_name='profile',
            name='technical_examiner',
            field=models.BooleanField(default=False, verbose_name='Технический экзаменатор'),
        ),
    ]
