# Generated by Django 4.2.11 on 2025-02-08 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_profile_scientific_examiner_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='rating',
            field=models.IntegerField(blank=True, null=True, verbose_name='Рейтинг'),
        ),
    ]
