# Generated by Django 4.2.11 on 2025-02-09 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_uploadedfile_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='download_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество скачиваний'),
        ),
    ]
