# Generated by Django 4.2.11 on 2025-02-11 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='direction',
            field=models.CharField(blank=True, choices=[('техническая', 'Техническа'), ('естественно-научная', 'Естественно-научная')], max_length=100, verbose_name='Направление'),
        ),
    ]
